:Author: shuvo961
:Email: {shovon961@gmail.com}
:Date: 20/06/2022
:Revision: version#
:License: Public Domain

= Project: {Tingu}

In this Arduino project tutorial we will create an obstacle-avoiding robot using the L298N h-bridge motor driver. We will also use the HC SR04 ultrasonic distance sensor for this project, as well as the NewPing library in the Arduino code.

== Step 1: Installation


For example:

1. Open this file
2. Edit as you like
3. Install NewPing library

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact shuvo961 https://id.arduino.cc/shuvo961

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
